import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import { NextIntlClientProvider } from "next-intl";
import {
  HydrationBoundary,
  dehydrate,
  QueryClient,
} from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchSessionFromServer() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/session`, {
    cache: "no-store",
  });
  if (!res.ok) return { user: null, error: `http_${res.status}` };
  return res.json() as Promise<{ user: any | null }>;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const qc = new QueryClient();
  const session = await fetchSessionFromServer();

  qc.setQueryData(["session"], session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextIntlClientProvider>
            <HydrationBoundary state={dehydrate(qc)}>
              {children}
            </HydrationBoundary>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
